package it.water.role.api;

import it.water.core.api.permission.Role;
import it.water.core.api.service.BaseEntityApi;

import it.water.role.model.WaterRole;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface RoleApi extends BaseEntityApi<WaterRole> {
    void addUserRole(long userId, Role role);
    void removeUserRole(long userId,Role role);
}