package it.water.role.api;

import it.water.core.api.repository.BaseRepository;
import it.water.role.model.WaterRole;

/**
 * @Generated by Water Generator
 * Interface component for Role Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface RoleRepository extends BaseRepository<WaterRole> {
}
