package it.water.role.service;

import it.water.core.api.permission.Role;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.permission.annotations.AllowGenericPermissions;
import it.water.repository.service.BaseEntityServiceImpl;
import it.water.role.actions.RoleActions;
import it.water.role.api.RoleApi;
import it.water.role.api.RoleSystemApi;
import it.water.role.model.WaterRole;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for Role entity.
 *
 */
@FrameworkComponent
public class RoleServiceImpl extends BaseEntityServiceImpl<WaterRole> implements RoleApi {

    @Inject
    @Getter
    @Setter
    private RoleSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public RoleServiceImpl() {
        super(WaterRole.class);
    }

    @Override
    @AllowGenericPermissions(actions = RoleActions.ASSIGN)
    public void addUserRole(long userId, Role role) {
        systemService.addUserRole(userId,role);
    }

    @Override
    @AllowGenericPermissions(actions = RoleActions.UNASSIGN)
    public void removeUserRole(long userId, Role role) {
        systemService.removeUserRole(userId,role);
    }
}
