package it.water.role.repository;

import it.water.core.api.model.PaginableResult;
import it.water.core.api.model.Role;
import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.repository.entity.model.exceptions.NoResultException;
import it.water.repository.jpa.WaterJpaRepositoryImpl;
import it.water.role.api.UserRoleRepository;
import it.water.role.model.WaterUserRole;
import jakarta.transaction.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * @Generated by Water Generator
 * Repository Class for Role entity.
 */
@FrameworkComponent
public class WaterUserRoleRepositoryImpl extends WaterJpaRepositoryImpl<WaterUserRole> implements UserRoleRepository {
    private static Logger logger = LoggerFactory.getLogger(WaterUserRoleRepositoryImpl.class);
    private static final String ROLE_PERSISTENCE_UNIT = "role-persistence-unit";

    public WaterUserRoleRepositoryImpl() {
        super(WaterUserRole.class, ROLE_PERSISTENCE_UNIT);
    }

    @Override
    public Collection<Role> findUserRoles(long userId) {
        Set<Role> roles = new HashSet<>();
        Query userRolesQuery = getQueryBuilderInstance().field("userId").equalTo(userId);
        PaginableResult<WaterUserRole> results = this.findAll(-1, -1, userRolesQuery, null);
        if (results != null)
            results.getResults().forEach(userRole -> roles.add(userRole.getRole()));
        return roles;
    }

    @Override
    public void removeUserRole(long userId, long roleId) {
        Query findUserRole = getQueryBuilderInstance().field("userId").equalTo(userId).and(getQueryBuilderInstance().field("role.id").equalTo(roleId));
        try {
            this.txExpr(Transactional.TxType.REQUIRED, entityManager -> {
                WaterUserRole waterUserRoles = this.find(findUserRole);
                this.remove(waterUserRoles.getId());
            });
        } catch (NoResultException e) {
            logger.debug("No role found for {}", userId);
        }
    }
}
