
package it.water.role.service.rest.spring;

import it.water.core.api.model.PaginableResult;
import it.water.core.api.repository.query.Query;
import it.water.core.api.repository.query.QueryOrder;
import it.water.role.api.rest.spring.RoleSpringRestApi;
import it.water.role.model.WaterRole;
import it.water.role.service.rest.RoleRestControllerImpl;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for User entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class RoleSpringRestControllerImpl extends RoleRestControllerImpl implements RoleSpringRestApi {
    @Override
    public void assignRole(long userId, long roleId) {
        super.assignRole(userId, roleId);
    }

    @Override
    public void unassignRole(long userId, long roleId) {
        super.unassignRole(userId, roleId);
    }

    @Override
    public WaterRole save(WaterRole entity) {
        return super.save(entity);
    }

    @Override
    public WaterRole update(WaterRole entity) {
        return super.update(entity);
    }

    @Override
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    public WaterRole find(long id) {
        return super.find(id);
    }

    @Override
    public PaginableResult<WaterRole> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    public PaginableResult<WaterRole> findAll() {
        return super.findAll();
    }
}
